config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index"
  resources :informations, only: [:index, :new, :create, :edit, :update, :show, :destroy] 
    
  resources :users, only: [:index, :edit, :new, :create, :update, :destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/information.rb
class Information < ApplicationRecord

#  validates :hypertension, diabetes, hyperlipidemia, liver_malfunction, kidney_malfunction, intracranial_hemorrhage, usage_antithrombotic, residence, activity_outside, activity_inside, presence: true
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController

  def index #今回は１人分のデータしか表示しないので必要ないかも
    @informations = Information.all
  end

  def new
    @information = Information.new
  end

  def create
    @information = Information.new(information_params)

    if @information.save
      redirect_to @information 
    else
      render :new
    end
  end

  def update
    @information = Information.find(params[:id])

    if @information.update(information_params)
      redirect_to @information
    else
      render :edit
    end

  end

  def destroy
    @information = Information.find(params[:id])
    information.destroy

    # redirect_to new_user_path #top pageに移動するように設定する
  end

  def edit
    @information = Information.find(params[:id])
  end

  def show
    @information = Information.find(params[:id])
  end

  private

  def information_params
   params.require(:information).permit(:intracranial_hemorrhage, :infraction_episodes, :usage_antithrombotic, :usage_antithrombotic, :hypertension, :medication_hypertension, :diabetes, :medication_diabetes, :hyperlipidemia, :medication_hyperlipidemia, :liver_malfunction, :kidney_malfunction, :residence, :activity_outside, :activity_inside)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :birthday)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/informations/destroy.html.haml
.contents-row
  .contents-row__success
    削除が完了しました。
    = link_to   <a class: "contents-row__success__btn" href="/">
      情報登録へ戻る

   

app/views/informations/detailed_registration.haml
.background
  .showname
    ＜userのname＞さんの情報を登録しています。

  .announce
    下記の情報を登録してください
    .announce__guide1
      「ある、ない」はどちらかを選択してください。
    .announce__guide2
      飲み薬の具体的な名前は空欄に記入してください。

  .medical-history-title
    <<病気の情報を教えてください>>

  .medical-history
    .medical-history__intracranial-hemorrhage
      脳出血やくも膜下出血になったことはありますか？
      .medical-history__intracranial-hemorrhage__selection-box
        <ある、なし>の選択を記載します。

    .medical-history__infraction-events
      脳梗塞もしくは心筋梗塞/狭心症にかかったことはありますか？
      .medical-history__infraction-events__selection-box
        <ある、なし>の選択を記載します。      
      .medical-history__infraction-events__antithrombotic
        血をサラサラにするお薬を飲んでいますか？
        .medical-history__infraction-events__antithrombotic__selection-box
          <ある、なし>の選択を記載します。
        .medical-history__infraction-events__antithrombotic__usage
          <薬の名前を教えてください>

    .medical-history__hypertension
      高血圧と言われたことがありますか？
      .medical-history__hypertension__selection-box
        <ある、なし>の選択を記載します。
      .medical-history__hypertension__medication
        <薬の名前を教えてください>

    .medical-history__diabetes
      糖尿病と言われたことがありますか？
      .medical-history__diabetes__selection-box
        <ある、なし>の選択を記載します。
      .medical-history__diabetes__medication
        <薬の名前を教えてください>

    .medical-history__hyperlipidemia
      高脂血症と言われたことがありますか？
      .medical-history__hyperlipidemia__selection-box
        <ある、なし>の選択を記載します。
      .medical-history__hyperlipidemia__medication
        <薬の名前を教えてください>

    .medical-history__kidney-malfunction
      腎機能障害（腎臓が悪い）と言われたことがありますか？
      .medical-history__kidney-malfunction__selection-box
        <ある、なし>の選択を記載します。

    .medical-history__liver-malfunction
      肝機能障害（肝臓が悪い）と言われたことがありますか？
      .medical-history__liver-malfunction__selection-box
        <ある、なし>の選択を記載します。
  .lifestyle-title
    <<現在の生活状況を簡単に教えてください>>

  .lifestyle
    .lifestyle__residence
      現在の住居はどちらですか？
      .lifestyle__residence__selection-box
        <自宅　自宅以外（施設、病院など）>
        
    .lifestyle__activity-outside
      普段外出はしていますか？
      .lifestyle__activity-outside__selection-box
        <一人で外出する　一人では外出できない>

    .lifestyle__activity-inside
      自宅内では普段どのように過ごしていますか？
      .lifestyle__activity-inside__selection-box
        <ほぼ自立　介助が必要>

app/views/informations/edit.html .haml
.background
  .showname
    ＜userのname＞さんの情報を登録しています。

  .announce
    下記の情報を登録してください
    .announce__guide1
      「ある、ない」はどちらかを選択してください。

  .medical-history-title
    <<病気の情報を教えてください>>

  .medical-history
    .medical-history__intracranial-hemorrhage
      脳出血やくも膜下出血になったことはありますか？
      .medical-history__intracranial-hemorrhage__selection-box
        <ある、なし>の選択を記載します。

    .medical-history__infraction-events
      脳梗塞もしくは心筋梗塞/狭心症にかかったことはありますか？
      .medical-history__infraction-events__selection-box
        <ある、なし>の選択を記載します。      
      .medical-history__infraction-events__antithrombotic
        血をサラサラにするお薬を飲んでいますか？
        .medical-history__infraction-events__antithrombotic__selection-box
          <ある、なし>の選択を記載します。

    .medical-history__hypertension
      高血圧と言われたことがありますか？
      .medical-history__hypertension__selection-box
        <ある、なし>の選択を記載します。

    .medical-history__diabetes
      糖尿病と言われたことがありますか？
      .medical-history__diabetes__selection-box
        <ある、なし>の選択を記載します。

    .medical-history__hyperlipidemia
      高脂血症と言われたことがありますか？
      .medical-history__hyperlipidemia__selection-box
        <ある、なし>の選択を記載します。

    .medical-history__kidney-malfunction
      腎機能障害（腎臓が悪い）と言われたことがありますか？
      .medical-history__kidney-malfunction__selection-box
        <ある、なし>の選択を記載します。

    .medical-history__liver-malfunction
      肝機能障害（肝臓が悪い）と言われたことがありますか？
      .medical-history__liver-malfunction__selection-box
        <ある、なし>の選択を記載します。

  .lifestyle-title
    <<現在の生活状況を簡単に教えてください>>

  .lifestyle
        
    .lifestyle__activity-outside
      普段外出はしていますか？
      .lifestyle__activity-outside__selection-box
        <一人で外出する　一人では外出できない>

    .lifestyle__activity-inside
      自宅内では普段どのように過ごしていますか？
      .lifestyle__activity-inside__selection-box
        <ほぼ自立　介助が必要>

app/views/informations/index.html.haml
.selections
  .selections__title
    登録の方法をお選びください
  .selections__simple
    らくらく登録
    /jump botton 装飾
  .selections__simple-explained
    飲み薬の詳細は登録しない方はこちら
  .selections__detail
    詳細登録
    /sign-in botton 装飾
  .selections__detail-explained
    飲み薬の詳細も登録したい方はこちら
  

app/views/informations/index2.html.haml
.background
  .registerd-informations
    ＜登録されている情報です＞
    .registerd-informations__nomesesso
      .registerd-informations__nomesesso__nome
        @information.nome さん
      .registerd-informations__nomesesso__sesso
        @information.sex 性
    .registerd-informations__etaanno
      .registerd-informations__etaanno__eta
        @information.age 才
      .registerd-informations__etaanno__anno
        @information.birthday 

  .storia
    ＜既往歴情報＞
    .storia__gruppo1
      .storia__gruppo1__emoraggio
        出血既往歴 @information.intracranial_hemorrhage
      .storia__gruppo1__embolo
        脳梗塞/心筋梗塞（狭心症） @information.infraction_episodes
      .storia__gruppo1__anticoagulante1
        抗血栓薬内服 @information.usage_antithrombotic
      .storia__gruppo1__anticoagulante2
        抗血栓薬内服 @information.usage_antithrombotic2

    .storia__gruppo2
      .storia__gruppo2__hypertension
        高血圧 @information.hypertension
      .storia__gruppo2__medication
        内服 @information.medication_hypertension

    .storia__gruppo3
      .storia__gruppo3__diabetes
        糖尿病 @information.diabetes
      .storia__gruppo3__medication
        内服 @information.medication_diabetes

    .storia__gruppo4
      .storia__gruppo4__hyperlipidemia
        高脂血症 @information.hyperlipidemia
      .storia__gruppo4__medication
        内服 @information.medication_hyperlipidemia

    .storia__gruppo5
      .storia__gruppo5__kidney
        腎機能障害 @information.kedney_malfunction

      .storia__gruppo5__liver
        肝機能障害 @information.liver_malfunction

  .vita
    ＜生活情報＞
    .vita__residenza
      生活環境 @information.residence
    .vita__fuori
      屋外生活 @information.activity_outside
    .vita__casa
      屋内生活 @information.activity_inside

  .modificare
    .modificare__modificare1
      ＜変更する＞
    .modificare__modificare2
      ＜削除する＞

app/views/informations/new.html.haml
.background
  .showname
    ＜userのname＞さんの情報を登録しています。

  .announce
    下記の情報を登録してください
    .announce__guide1
      「ある、ない」はどちらかを選択してください。

  .medical-history-title
    <<病気の情報を教えてください>>

  .medical-history
    .medical-history__intracranial-hemorrhage
      脳出血やくも膜下出血になったことはありますか？
      .medical-history__intracranial-hemorrhage__selection-box
        <ある、なし>の選択を記載します。

    .medical-history__infraction-events
      脳梗塞もしくは心筋梗塞/狭心症にかかったことはありますか？
      .medical-history__infraction-events__selection-box
        <ある、なし>の選択を記載します。      
      .medical-history__infraction-events__antithrombotic
        血をサラサラにするお薬を飲んでいますか？
        .medical-history__infraction-events__antithrombotic__selection-box
          <ある、なし>の選択を記載します。

    .medical-history__hypertension
      高血圧と言われたことがありますか？
      .medical-history__hypertension__selection-box
        <ある、なし>の選択を記載します。

    .medical-history__diabetes
      糖尿病と言われたことがありますか？
      .medical-history__diabetes__selection-box
        <ある、なし>の選択を記載します。

    .medical-history__hyperlipidemia
      高脂血症と言われたことがありますか？
      .medical-history__hyperlipidemia__selection-box
        <ある、なし>の選択を記載します。

    .medical-history__kidney-malfunction
      腎機能障害（腎臓が悪い）と言われたことがありますか？
      .medical-history__kidney-malfunction__selection-box
        <ある、なし>の選択を記載します。

    .medical-history__liver-malfunction
      肝機能障害（肝臓が悪い）と言われたことがありますか？
      .medical-history__liver-malfunction__selection-box
        <ある、なし>の選択を記載します。

  .lifestyle-title
    <<現在の生活状況を簡単に教えてください>>

  .lifestyle
        
    .lifestyle__activity-outside
      普段外出はしていますか？
      .lifestyle__activity-outside__selection-box
        <一人で外出する　一人では外出できない>

    .lifestyle__activity-inside
      自宅内では普段どのように過ごしていますか？
      .lifestyle__activity-inside__selection-box
        <ほぼ自立　介助が必要>
  
  .submission

　/to do 登録のボタンを作る
  

app/views/informations/show.html.haml
.background
  .registerd-informations
    ＜登録されている情報です＞
    .registerd-informations__nomesesso
      .registerd-informations__nomesesso__nome
        @user.username 性
      .registerd-informations__nomesesso__sesso
        @user.sex 性
    .registerd-informations__etaanno
      .registerd-informations__etaanno__eta
        @user.age 才
      .registerd-informations__etaanno__anno
        @user.birthday 

  .storia
    ＜既往歴情報＞
    .storia__gruppo1
      .storia__gruppo1__emoraggio
        出血既往歴 @information.intracranial_hemorrhage
      .storia__gruppo1__embolo
        脳梗塞/心筋梗塞（狭心症） @information.infraction_episodes
      .storia__gruppo1__anticoagulante1
        抗血栓薬内服 @information.usage_antithrombotic
      .storia__gruppo1__anticoagulante2
        抗血栓薬内服 @information.usage_antithrombotic

    .storia__gruppo2
      .storia__gruppo2__hypertension
        高血圧 @information.hypertension
      .storia__gruppo2__medication
        内服 @information.medication_hypertension

    .storia__gruppo3
      .storia__gruppo3__diabetes
        糖尿病 @information.diabetes
      .storia__gruppo3__medication
        内服 @information.medication_diabetes

    .storia__gruppo4
      .storia__gruppo4__hyperlipidemia
        高脂血症 @information.hyperlipidemia
      .storia__gruppo4__medication
        内服 @information.medication_hyperlipidemia

    .storia__gruppo5
      .storia__gruppo5__kidney
        腎機能障害 @information.kedney_malfunction

      .storia__gruppo5__liver
        肝機能障害 @information.liver_malfunction

  .vita
    ＜生活情報＞
    .vita__residenza
      生活環境 @information.residence
    .vita__fuori
      屋外生活 @information.activity_outside
    .vita__casa
      屋内生活 @information.activity_inside

    
  .modificare
    = link_to "＜編集する＞", edit_information_path, method: :get, class: "modificare__modificare1"
    = link_to "＜削除する＞", delete_information_path, method: :delete, class: "modificare__modificare2"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MinimumInformationsStrokepatients
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/users/edit.html.haml
.userdata
  .userdata__title
    入力情報

  .userdata__name-tag
    名前
    .userdata__name-tag__data
      <名前を入力してください>

  .userdata__password-tag
    パスワード
    .userdata__password-tag__data
      <パスワードを入力してください>

  .userdata__age-tag
    年齢
    .userdata__age-tag__data
      <年齢を入力してください>歳

  .userdata__birthday-tag
    誕生日
    .userdata__birthday-tag__data
      <誕生日を入力してください>

  .userdata__sex-tag
    性別
    .userdata__sex-tag__data
      <性別を選択してください>
  

app/views/users/index.html.haml
.language-selection
  .language-selection__box
    日本語

.title
  .title__phrase
    誰でもラクラク登録できる基本病歴情報（Stroke）

.login-box
  .login-box__nametitle
    名前
  .login-box__nameblank
    (名前を入力してください)

  .login-box__passwordtitle
    パスワード
  .login-box__passwordblank
    (パスワードを入力してください)

  .login-box__status
    = link_to "＜初めての方（新規登録）＞", new_user_registration_path, method: :get, class: "login-box__status__first-time"
    = link_to "＜２回目以降の方はこちら＞", user_session, method: :post, class: "login-box__status__registered-before"
     

app/views/users/new.html.haml
.language-selection
  .language-selection__box
    日本語

.title
  .title__phrase
    誰でもラクラク登録できる基本病歴情報（Stroke）

.login-box
  .login-box__nametitle
    名前
  .login-box__nameblank
    (名前を入力してください)

  .login-box__passwordtitle
    パスワード
  .login-box__passwordblank
    (パスワードを入力してください)

  .login-box__status
    .login-box__status__first-time
      初めての方（新規登録）
      /sign-in botton 装飾
    .login-box__status__registered-before
      ２回目以降の方はこちら
      /log-in botton 装飾

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:birthday && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/